#!/bin/bash

# ===================================================================
# PostgreSQL Backup Script
# Auto-generated by bootstrap-postgres.sh
# ===================================================================

set -euo pipefail

# Configuration
DB_NAME="{{DB_NAME}}"
DB_USER="{{DB_USER}}"
DB_PASSWORD="{{DB_PASSWORD}}"
DB_HOST="{{DB_HOST}}"
DB_PORT="{{DB_PORT}}"

BACKUP_DIR="./database/backups"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="${BACKUP_DIR}/${DB_NAME}_${TIMESTAMP}.sql"

# ===================================================================
# Backup Functions
# ===================================================================

backup_database() {
    local backup_path="$1"

    echo "Starting backup of $DB_NAME..."

    # Create backup directory
    mkdir -p "$BACKUP_DIR"

    # Export password
    export PGPASSWORD="$DB_PASSWORD"

    # Run pg_dump
    if pg_dump \
        -h "$DB_HOST" \
        -p "$DB_PORT" \
        -U "$DB_USER" \
        "$DB_NAME" > "$backup_path"; then
        echo "✓ Backup completed: $backup_path"

        # Compress
        if gzip "$backup_path"; then
            echo "✓ Compressed: ${backup_path}.gz"
            BACKUP_FILE="${backup_path}.gz"
        fi
        return 0
    else
        echo "✗ Backup failed"
        return 1
    fi
}

cleanup_old_backups() {
    echo "Cleaning up old backups (keeping last 7 days)..."
    find "$BACKUP_DIR" -name "${DB_NAME}_*.sql.gz" -mtime +7 -delete 2>/dev/null || true
    echo "✓ Cleanup complete"
}

# ===================================================================
# Main
# ===================================================================

if backup_database "$BACKUP_FILE"; then
    cleanup_old_backups
    echo ""
    echo "Database backup successful!"
    echo "Location: ${BACKUP_FILE}.gz"
    ls -lh "${BACKUP_FILE}.gz"
else
    echo "✗ Backup failed"
    exit 1
fi
