#!/bin/bash

# ===================================================================
# bootstrap-redis.sh
#
# Purpose: Redis cache/session store setup with file tracking
# Creates: Docker Compose config, Redis configuration, backups, env files
# Config:  [redis] section in bootstrap.config
# ===================================================================

set -euo pipefail

# ===================================================================
# Setup
# ===================================================================

# Get script directory and bootstrap root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOTSTRAP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Source common library
source "${BOOTSTRAP_DIR}/lib/common.sh"

# Initialize script
init_script "bootstrap-redis"

# Get project root from argument or current directory
PROJECT_ROOT=$(get_project_root "${1:-.}")

# Script identifier for logging
SCRIPT_NAME="bootstrap-redis"

# Track created files for display
declare -a CREATED_FILES=()
declare -a SKIPPED_FILES=()

# ===================================================================
# Read Configuration
# ===================================================================

# Check if this bootstrap should run
ENABLED=$(config_get "redis.enabled" "true")
if [[ "$ENABLED" != "true" ]]; then
    log_info "Redis bootstrap disabled in config"
    exit 0
fi

# Read Redis-specific settings
REDIS_VERSION=$(config_get "redis.version" "latest")
REDIS_HOST=$(config_get "redis.host" "localhost")
REDIS_PORT=$(config_get "redis.port" "6379")
REDIS_PASSWORD=$(config_get "redis.password" "redis_password")
MAX_MEMORY=$(config_get "redis.max_memory" "256mb")
MAX_CLIENTS=$(config_get "redis.max_clients" "10000")
BACKUP_ENABLED=$(config_get "redis.backup_enabled" "true")
BACKUP_RETENTION=$(config_get "redis.backup_retention_days" "30")
PERSISTENCE=$(config_get "redis.persistence" "yes")

# Get project name for Docker
PROJECT_NAME=$(config_get "project.name" "app")

# ===================================================================
# Pre-Execution Confirmation
# ===================================================================

FILES_TO_CREATE=(
    "config/redis/"
    "config/redis/redis.conf"
    "config/redis/backup.sh"
    ".env.redis"
    "docker-compose.redis.yml"
    "backups/redis/"
)

pre_execution_confirm "$SCRIPT_NAME" "Redis Configuration" \
    "${FILES_TO_CREATE[@]}"

# ===================================================================
# Validation
# ===================================================================

log_info "Validating environment..."

# Check if project directory exists
require_dir "$PROJECT_ROOT" || log_fatal "Project directory not found: $PROJECT_ROOT"

# Check if we can write to project
is_writable "$PROJECT_ROOT" || log_fatal "Project directory not writable: $PROJECT_ROOT"

log_success "Environment validated"

# ===================================================================
# Create Directory Structure
# ===================================================================

log_info "Creating Redis directory structure..."

if ! dir_exists "$PROJECT_ROOT/config/redis"; then
    ensure_dir "$PROJECT_ROOT/config/redis"
    log_dir_created "$SCRIPT_NAME" "config/redis/"
fi

if ! dir_exists "$PROJECT_ROOT/backups/redis"; then
    ensure_dir "$PROJECT_ROOT/backups/redis"
    log_dir_created "$SCRIPT_NAME" "backups/redis/"
fi

log_success "Directory structure created"

# ===================================================================
# Create Redis Configuration File
# ===================================================================

log_info "Creating Redis configuration..."

REDIS_CONF_FILE="$PROJECT_ROOT/config/redis/redis.conf"

if file_exists "$REDIS_CONF_FILE"; then
    backup_file "$REDIS_CONF_FILE"
    SKIPPED_FILES+=("config/redis/redis.conf (backed up)")
    log_warning "redis.conf already exists, backed up"
else
    cat > "$REDIS_CONF_FILE" << 'EOFCONF'
# ===================================================================
# Redis Configuration
# Auto-generated by bootstrap-redis.sh
# ===================================================================

# Network
bind 0.0.0.0
port 6379

# Password protection (change in production!)
requirepass {{REDIS_PASSWORD}}

# Memory management
maxmemory {{MAX_MEMORY}}
maxmemory-policy allkeys-lru

# Persistence - AOF (Append Only File)
appendonly yes
appendfsync everysec
appendfilename "appendonly.aof"

# Persistence - RDB (Snapshots)
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb

# Logging
loglevel notice
logfile ""

# Database
databases 16
default-db 0

# Timeouts
timeout 0
tcp-backlog 511

# Client handling
maxclients {{MAX_CLIENTS}}

# Eviction (when max memory is reached)
# allkeys-lru: Remove any key using LRU algorithm
# volatile-lru: Remove only keys with TTL using LRU

# Replication (for clustering, not enabled by default)
# replicaof <masterip> <masterport>
replica-serve-stale-data yes
replica-read-only yes

# Security
# requirepass is set above

# Performance
always-show-logo no

# Keys notification (for pub/sub key events)
notify-keyspace-events ""

# Lazy freeing (async deletion)
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no

# Active rehashing
activerehashing yes

# Client output buffer limits
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60

# Frequency of rehashing the main dict
hz 10

# AOF rewrite incremental fsync
aof-rewrite-incremental-fsync yes
EOFCONF

    # Replace placeholders
    sed -i "s/{{REDIS_PASSWORD}}/$REDIS_PASSWORD/g" "$REDIS_CONF_FILE"
    sed -i "s/{{MAX_MEMORY}}/$MAX_MEMORY/g" "$REDIS_CONF_FILE"
    sed -i "s/{{MAX_CLIENTS}}/$MAX_CLIENTS/g" "$REDIS_CONF_FILE"

    verify_file "$REDIS_CONF_FILE"
    log_file_created "$SCRIPT_NAME" "config/redis/redis.conf"
    CREATED_FILES+=("config/redis/redis.conf")
fi

# ===================================================================
# Create Backup Script
# ===================================================================

if [[ "$BACKUP_ENABLED" == "true" ]]; then
    log_info "Creating Redis backup script..."

    BACKUP_SCRIPT="$PROJECT_ROOT/config/redis/backup.sh"

    if file_exists "$BACKUP_SCRIPT"; then
        backup_file "$BACKUP_SCRIPT"
        SKIPPED_FILES+=("config/redis/backup.sh (backed up)")
        log_warning "backup.sh already exists, backed up"
    else
        cat > "$BACKUP_SCRIPT" << 'EOFBACKUP'
#!/bin/bash

# ===================================================================
# Redis Backup and Snapshot Script
# Auto-generated by bootstrap-redis.sh
# ===================================================================

set -euo pipefail

# Configuration
REDIS_HOST="{{REDIS_HOST}}"
REDIS_PORT="{{REDIS_PORT}}"
REDIS_PASSWORD="{{REDIS_PASSWORD}}"

BACKUP_DIR="./backups/redis"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="${BACKUP_DIR}/redis_${TIMESTAMP}.rdb"

# ===================================================================
# Backup Functions
# ===================================================================

backup_redis() {
    echo "Starting Redis backup..."

    # Create backup directory
    mkdir -p "$BACKUP_DIR"

    # Trigger Redis BGSAVE (background save)
    if [[ -n "$REDIS_PASSWORD" ]]; then
        redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" -a "$REDIS_PASSWORD" BGSAVE 2>/dev/null || echo "Could not connect to Redis"
    else
        redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" BGSAVE 2>/dev/null || echo "Could not connect to Redis"
    fi

    echo "✓ Backup triggered"
}

cleanup_old_backups() {
    echo "Cleaning up old backups (keeping last 30 days)..."
    find "$BACKUP_DIR" -name "redis_*.rdb" -mtime +30 -delete 2>/dev/null || true
    find "$BACKUP_DIR" -name "redis_*.tar.gz" -mtime +30 -delete 2>/dev/null || true
    echo "✓ Cleanup complete"
}

get_redis_info() {
    echo ""
    echo "Redis Status:"
    if [[ -n "$REDIS_PASSWORD" ]]; then
        redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" -a "$REDIS_PASSWORD" INFO server 2>/dev/null | grep -E "redis_version|uptime|connected_clients" || echo "Status unavailable"
    else
        redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" INFO server 2>/dev/null | grep -E "redis_version|uptime|connected_clients" || echo "Status unavailable"
    fi
}

# ===================================================================
# Main
# ===================================================================

echo "Redis Backup Tool"
echo "================="
echo ""

backup_redis
cleanup_old_backups
get_redis_info

echo ""
echo "Backup directory: $BACKUP_DIR"
ls -lh "$BACKUP_DIR" 2>/dev/null | tail -5 || echo "  (no backups yet)"
EOFBACKUP

        # Replace placeholders
        sed -i "s/{{REDIS_HOST}}/$REDIS_HOST/g" "$BACKUP_SCRIPT"
        sed -i "s/{{REDIS_PORT}}/$REDIS_PORT/g" "$BACKUP_SCRIPT"
        sed -i "s/{{REDIS_PASSWORD}}/$REDIS_PASSWORD/g" "$BACKUP_SCRIPT"

        chmod +x "$BACKUP_SCRIPT"

        verify_file "$BACKUP_SCRIPT"
        log_file_created "$SCRIPT_NAME" "config/redis/backup.sh"
        CREATED_FILES+=("config/redis/backup.sh")
    fi
fi

# ===================================================================
# Create Environment File
# ===================================================================

log_info "Creating Redis environment configuration..."

ENV_FILE="$PROJECT_ROOT/.env.redis"

if file_exists "$ENV_FILE"; then
    backup_file "$ENV_FILE"
    SKIPPED_FILES+=(".env.redis (backed up)")
    log_warning ".env.redis already exists, backed up"
else
    cat > "$ENV_FILE" << 'EOFENV'
# ===================================================================
# Redis Environment Configuration
# Auto-generated by bootstrap-redis.sh
# ===================================================================

# Connection
REDIS_HOST={{REDIS_HOST}}
REDIS_PORT={{REDIS_PORT}}
REDIS_URL=redis://{{REDIS_HOST}}:{{REDIS_PORT}}
REDIS_PASSWORD={{REDIS_PASSWORD}}

# Security
REDIS_TLS=false

# Performance
REDIS_POOL_SIZE=10
REDIS_CONNECTION_TIMEOUT=5000
REDIS_IDLE_TIMEOUT=60000
REDIS_RETRY_STRATEGY=exponential

# Cache settings
REDIS_TTL=3600
REDIS_MAX_RETRIES=3

# Logging
REDIS_DEBUG=false
REDIS_LOG_COMMANDS=false
EOFENV

    # Replace placeholders
    sed -i "s/{{REDIS_HOST}}/$REDIS_HOST/g" "$ENV_FILE"
    sed -i "s/{{REDIS_PORT}}/$REDIS_PORT/g" "$ENV_FILE"
    sed -i "s/{{REDIS_PASSWORD}}/$REDIS_PASSWORD/g" "$ENV_FILE"

    verify_file "$ENV_FILE"
    log_file_created "$SCRIPT_NAME" ".env.redis"
    CREATED_FILES+=(".env.redis")
fi

# ===================================================================
# Create Docker Compose Configuration
# ===================================================================

log_info "Creating Docker Compose configuration..."

DOCKER_COMPOSE_FILE="$PROJECT_ROOT/docker-compose.redis.yml"

if file_exists "$DOCKER_COMPOSE_FILE"; then
    backup_file "$DOCKER_COMPOSE_FILE"
    SKIPPED_FILES+=("docker-compose.redis.yml (backed up)")
    log_warning "docker-compose.redis.yml already exists, backed up"
else
    cat > "$DOCKER_COMPOSE_FILE" << 'EOFDOCKER'
version: '3.8'

services:
  redis:
    image: redis:{{REDIS_VERSION}}-alpine
    container_name: {{PROJECT_NAME}}-redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass {{REDIS_PASSWORD}}
    ports:
      - "{{REDIS_PORT}}:6379"
    volumes:
      - redis_data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - {{PROJECT_NAME}}-net
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  {{PROJECT_NAME}}-net:
    driver: bridge
EOFDOCKER

    # Replace placeholders
    sed -i "s/{{REDIS_VERSION}}/$REDIS_VERSION/g" "$DOCKER_COMPOSE_FILE"
    sed -i "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$DOCKER_COMPOSE_FILE"
    sed -i "s/{{REDIS_PASSWORD}}/$REDIS_PASSWORD/g" "$DOCKER_COMPOSE_FILE"
    sed -i "s/{{REDIS_PORT}}/$REDIS_PORT/g" "$DOCKER_COMPOSE_FILE"

    verify_file "$DOCKER_COMPOSE_FILE"
    log_file_created "$SCRIPT_NAME" "docker-compose.redis.yml"
    CREATED_FILES+=("docker-compose.redis.yml")
fi

# ===================================================================
# Display Created Files
# ===================================================================

log_script_complete "$SCRIPT_NAME" "${#CREATED_FILES[@]} files created"

echo ""
log_section "Redis Bootstrap Complete"

echo -e "${GREEN}✓ Created Files:${NC}"
for file in "${CREATED_FILES[@]}"; do
    echo "  • $file"
done

if [[ ${#SKIPPED_FILES[@]} -gt 0 ]]; then
    echo ""
    echo -e "${YELLOW}⚠ Skipped Files (already existed):${NC}"
    for file in "${SKIPPED_FILES[@]}"; do
        echo "  • $file"
    done
fi

# ===================================================================
# Summary
# ===================================================================

echo ""
echo -e "${BLUE}Redis Configuration:${NC}"
echo "  Host: $REDIS_HOST"
echo "  Port: $REDIS_PORT"
echo "  Password: $REDIS_PASSWORD"
echo "  Max Memory: $MAX_MEMORY"
echo "  Max Clients: $MAX_CLIENTS"
echo "  Persistence: $PERSISTENCE"
echo ""

echo -e "${BLUE}Quick Start:${NC}"
echo "  1. Start Redis container:"
echo "     docker-compose -f docker-compose.redis.yml up -d"
echo ""
echo "  2. Verify connection:"
echo "     docker-compose -f docker-compose.redis.yml exec redis redis-cli -a $REDIS_PASSWORD ping"
echo ""
echo "  3. Run backups:"
echo "     bash config/redis/backup.sh"
echo ""

echo -e "${BLUE}Files Created:${NC}"
echo "  Total: ${#CREATED_FILES[@]} files"
echo "  Location: $PROJECT_ROOT"
echo ""

echo -e "${YELLOW}Security Reminder:${NC}"
echo "  • Change REDIS_PASSWORD in .env.redis (current: $REDIS_PASSWORD)"
echo "  • Never commit .env.redis to git"
echo "  • Use environment variables for production"
echo "  • Enable Redis AUTH (password) in production"
echo "  • Consider using Redis ACL (Redis 6+) for multi-user scenarios"
echo ""

show_log_location
