"""
{{PROJECT_NAME_PASCAL}} Test Configuration

Pytest fixtures and configuration for the test suite.
Generated by bootstrap-test-suite.sh
"""

import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import pytest

# ===================================================================
# Path Setup
# ===================================================================

ROOT_DIR = Path(__file__).resolve().parent.parent  # Project root
PROJECT_ROOT = ROOT_DIR.parent  # Repo root (if different)

# Ensure project is importable
for path_str in (str(PROJECT_ROOT), str(ROOT_DIR)):
    if path_str in sys.path:
        sys.path.remove(path_str)
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(1, str(ROOT_DIR))

# ===================================================================
# Conditional Storage Import
# ===================================================================

try:
    from {{SRC_DIR}}.storage import Storage
    HAS_STORAGE = True
except ImportError:
    HAS_STORAGE = False
    Storage = None

# ===================================================================
# Test Logs Configuration
# ===================================================================

TEST_LOGS_DIR = Path(__file__).resolve().parent / "logs"
_current_log_dir = None


def cleanup_old_test_logs(keep_last: int = 3):
    """Remove old test log directories, keeping only the last N runs."""
    if not TEST_LOGS_DIR.exists():
        return

    log_dirs = sorted(
        [d for d in TEST_LOGS_DIR.iterdir() if d.is_dir() and d.name != "latest"],
        key=lambda x: x.stat().st_mtime,
        reverse=True,
    )

    for old_dir in log_dirs[keep_last:]:
        for file in old_dir.iterdir():
            file.unlink()
        old_dir.rmdir()


def pytest_configure(config):
    """Configure pytest at startup to set logging paths."""
    global _current_log_dir

    TEST_LOGS_DIR.mkdir(exist_ok=True)
    cleanup_old_test_logs(keep_last=3)

    timestamp = datetime.now(ZoneInfo("{{TZ}}")).strftime("%m-%d-%Y_%I-%M%p")
    log_dir = TEST_LOGS_DIR / timestamp
    log_dir.mkdir(exist_ok=True)
    _current_log_dir = log_dir

    # Create 'latest' symlink
    latest_dir = TEST_LOGS_DIR / "latest"
    if latest_dir.exists() or latest_dir.is_symlink():
        if latest_dir.is_symlink():
            latest_dir.unlink()
        elif latest_dir.is_dir():
            for file in latest_dir.iterdir():
                file.unlink()
            latest_dir.rmdir()

    if not latest_dir.exists():
        latest_dir.symlink_to(timestamp, target_is_directory=True)

    # Set log file path
    log_file = log_dir / "pytest.log"
    config.option.log_file = str(log_file)
    config.option.log_file_level = "INFO"

    # Set junit XML path
    junit_file = log_dir / "junit_report.xml"
    config.option.xmlpath = str(junit_file)


def pytest_sessionfinish(session, exitstatus):
    """Save a human-readable test summary after session ends."""
    global _current_log_dir

    if _current_log_dir is None or not _current_log_dir.exists():
        return

    log_dir = _current_log_dir
    summary_file = log_dir / "test_summary.txt"

    stats = session.testscollected

    with open(summary_file, "w") as f:
        f.write("Test Run Summary\n")
        f.write("=" * 80 + "\n")
        f.write(f"Timestamp: {datetime.now(ZoneInfo('{{TZ}}')).strftime('%m-%d-%Y %I:%M:%S %p')}\n")
        f.write(f"Total Tests Collected: {stats}\n")
        f.write(f"Exit Status: {exitstatus}\n")
        f.write("=" * 80 + "\n\n")
        f.write("Exit codes:\n")
        f.write("  0 = All tests passed\n")
        f.write("  1 = Tests failed\n")
        f.write("  2 = Test execution interrupted\n")
        f.write("  3 = Internal error\n")
        f.write("  4 = Command line usage error\n")
        f.write("  5 = No tests collected\n\n")
        f.write("Detailed results available in:\n")
        f.write(f"  {log_dir / 'junit_report.xml'}\n")
        f.write(f"  {log_dir / 'pytest.log'}\n")


# ===================================================================
# Database Fixtures
# ===================================================================

@pytest.fixture
def temp_db_path(tmp_path):
    """Temporary database path for isolated tests."""
    return tmp_path / "{{PROJECT_NAME_SNAKE}}_test.db"


@pytest.fixture
def storage(temp_db_path):
    """Storage instance with temporary database."""
    if not HAS_STORAGE:
        pytest.skip("Storage module not found - skipping storage tests")

    store = Storage(str(temp_db_path))
    store.init_db()
    yield store

    # Cleanup database artifacts
    for suffix in ("", "-wal", "-shm"):
        db_file = temp_db_path.with_name(temp_db_path.name + suffix)
        if db_file.exists():
            db_file.unlink()


# ===================================================================
# Project Fixtures (customize as needed)
# ===================================================================

@pytest.fixture
def project(storage):
    """Create a test project."""
    if not HAS_STORAGE:
        pytest.skip("Storage module not found")
    return storage.create_project(
        name="test-project",
        repo_path="/tmp/repo",
        prd_path="/tmp/prd",
    )


@pytest.fixture
def session(storage, project):
    """Create a test session."""
    if not HAS_STORAGE:
        pytest.skip("Storage module not found")
    return storage.create_session(
        name="test-session",
        description="Session for unit tests",
    )


@pytest.fixture
def queue(storage, session):
    """Create a test queue."""
    if not HAS_STORAGE:
        pytest.skip("Storage module not found")
    return storage.create_queue(
        session_id=session["id"],
        name="test-queue",
        instructions="Queue for unit tests",
    )


@pytest.fixture
def task(storage, queue):
    """Create a test task."""
    if not HAS_STORAGE:
        pytest.skip("Storage module not found")
    return storage.create_task(
        queue_id=queue["id"],
        tool_name="test-tool",
        task_class="test-class",
        payload='{"test": true}',
        timeout=300,
    )
