/**
 * {{PROJECT_NAME_PASCAL}} Jest Setup
 *
 * Global setup for Jest test suite.
 * Generated by bootstrap-test-suite.sh
 */

// Increase timeout for browser tests
jest.setTimeout(30000);

// Global test utilities
global.testUtils = {
  /**
   * Wait for a condition to be true
   * @param {Function} condition - Function that returns boolean
   * @param {number} timeout - Max wait time in ms
   * @param {number} interval - Check interval in ms
   */
  async waitFor(condition, timeout = 5000, interval = 100) {
    const start = Date.now();
    while (Date.now() - start < timeout) {
      if (await condition()) return true;
      await new Promise(r => setTimeout(r, interval));
    }
    throw new Error(`Condition not met within ${timeout}ms`);
  },

  /**
   * Sleep for specified milliseconds
   * @param {number} ms - Milliseconds to sleep
   */
  sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  },

  /**
   * Generate a unique test ID
   * @param {string} prefix - ID prefix
   */
  uniqueId(prefix = 'test') {
    return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  }
};

// Console error tracking
const originalError = console.error;
let consoleErrors = [];

beforeEach(() => {
  consoleErrors = [];
  console.error = (...args) => {
    consoleErrors.push(args);
    originalError.apply(console, args);
  };
});

afterEach(() => {
  console.error = originalError;
  // Uncomment to fail tests on console errors:
  // if (consoleErrors.length > 0) {
  //   throw new Error(`Console errors detected: ${JSON.stringify(consoleErrors)}`);
  // }
});

// Global teardown
afterAll(async () => {
  // Cleanup any lingering resources
});
