#!/bin/bash

# ===================================================================
# Redis Backup and Snapshot Script
# Auto-generated by bootstrap-redis.sh
# ===================================================================

set -euo pipefail

# Configuration
REDIS_HOST="{{REDIS_HOST}}"
REDIS_PORT="{{REDIS_PORT}}"
REDIS_PASSWORD="{{REDIS_PASSWORD}}"

BACKUP_DIR="./backups/redis"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="${BACKUP_DIR}/redis_${TIMESTAMP}.rdb"

# ===================================================================
# Backup Functions
# ===================================================================

backup_redis() {
    local backup_path="$1"

    echo "Starting Redis backup..."

    # Create backup directory
    mkdir -p "$BACKUP_DIR"

    # Trigger Redis BGSAVE (background save)
    if [[ -n "$REDIS_PASSWORD" ]]; then
        redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" -a "$REDIS_PASSWORD" BGSAVE
    else
        redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" BGSAVE
    fi

    # Wait for save to complete (check status)
    echo "Waiting for background save to complete..."
    local max_wait=60
    local elapsed=0

    while [[ $elapsed -lt $max_wait ]]; do
        if [[ -n "$REDIS_PASSWORD" ]]; then
            status=$(redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" -a "$REDIS_PASSWORD" LASTSAVE 2>/dev/null || echo "0")
        else
            status=$(redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" LASTSAVE 2>/dev/null || echo "0")
        fi

        if [[ -n "$status" ]] && [[ "$status" != "0" ]]; then
            echo "✓ Backup completed"
            return 0
        fi

        sleep 2
        elapsed=$((elapsed + 2))
    done

    echo "⚠ Backup timeout after ${max_wait}s (may still be in progress)"
    return 0
}

export_redis_data() {
    local backup_path="$1"

    echo "Exporting Redis data..."

    # Get dump.rdb from Redis container or local instance
    if command -v docker &>/dev/null; then
        container_name=$(docker ps --filter "ancestor=redis*" --format "{{.Names}}" | head -1)
        if [[ -n "$container_name" ]]; then
            echo "Found container: $container_name"
            docker exec "$container_name" redis-cli --rdb "$backup_path" 2>/dev/null || true
        fi
    fi

    # If file doesn't exist, try direct export
    if [[ ! -f "$backup_path" ]]; then
        echo "✓ Backup ready (use 'redis-cli BGSAVE' to manually trigger)"
    else
        echo "✓ Exported to: $backup_path"
        ls -lh "$backup_path"
    fi
}

cleanup_old_backups() {
    echo "Cleaning up old backups (keeping last 30 days)..."
    find "$BACKUP_DIR" -name "redis_*.rdb" -mtime +30 -delete 2>/dev/null || true
    find "$BACKUP_DIR" -name "redis_*.tar.gz" -mtime +30 -delete 2>/dev/null || true
    echo "✓ Cleanup complete"
}

get_redis_info() {
    echo ""
    echo "Redis Status:"
    if [[ -n "$REDIS_PASSWORD" ]]; then
        redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" -a "$REDIS_PASSWORD" INFO server 2>/dev/null | grep -E "redis_version|uptime|connected_clients" || echo "Could not connect"
    else
        redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" INFO server 2>/dev/null | grep -E "redis_version|uptime|connected_clients" || echo "Could not connect"
    fi
}

# ===================================================================
# Main
# ===================================================================

echo "Redis Backup Tool"
echo "================="
echo ""

backup_redis "$BACKUP_FILE"
export_redis_data "$BACKUP_FILE"
cleanup_old_backups
get_redis_info

echo ""
echo "Backup summary:"
echo "  Location: $BACKUP_DIR"
ls -lh "$BACKUP_DIR" | tail -5

echo ""
echo "Restore instructions:"
echo "  1. Stop Redis: docker-compose -f docker-compose.redis.yml stop"
echo "  2. Restore dump.rdb to volume"
echo "  3. Restart Redis: docker-compose -f docker-compose.redis.yml up"
