/**
 * {{PROJECT_NAME_PASCAL}} Playwright Setup
 *
 * Global setup and fixtures for Playwright tests.
 * Generated by bootstrap-test-suite.sh
 */

import { test as base, expect } from '@playwright/test';

// Extend base test with custom fixtures
export const test = base.extend<{
  // Add custom fixtures here
  authenticatedPage: typeof base;
}>({
  // Example: authenticated page fixture
  // authenticatedPage: async ({ page }, use) => {
  //   await page.goto('/login');
  //   await page.fill('[name="email"]', 'test@example.com');
  //   await page.fill('[name="password"]', 'password');
  //   await page.click('button[type="submit"]');
  //   await page.waitForURL('/dashboard');
  //   await use(page);
  // },
});

// Re-export expect for convenience
export { expect };

// Custom matchers
expect.extend({
  /**
   * Check if element has specific data attribute
   */
  async toHaveDataAttribute(locator, attribute: string, value?: string) {
    const element = await locator.elementHandle();
    const actualValue = await element?.getAttribute(`data-${attribute}`);

    if (value === undefined) {
      return {
        pass: actualValue !== null,
        message: () => `expected element to have data-${attribute} attribute`,
      };
    }

    return {
      pass: actualValue === value,
      message: () =>
        `expected data-${attribute} to be "${value}", got "${actualValue}"`,
    };
  },
});

// Global test hooks
test.beforeEach(async ({ page }) => {
  // Add console error tracking
  page.on('console', msg => {
    if (msg.type() === 'error') {
      console.error('Browser console error:', msg.text());
    }
  });

  // Track page errors
  page.on('pageerror', error => {
    console.error('Page error:', error.message);
  });
});

// Test utilities
export const utils = {
  /**
   * Wait for network idle
   */
  async waitForNetworkIdle(page: typeof base, timeout = 5000) {
    await page.waitForLoadState('networkidle', { timeout });
  },

  /**
   * Take a screenshot with timestamp
   */
  async screenshot(page: typeof base, name: string) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    await page.screenshot({
      path: `{{TESTS_DIR}}/logs/latest/screenshots/${name}-${timestamp}.png`,
      fullPage: true,
    });
  },

  /**
   * Generate unique test data
   */
  uniqueId(prefix = 'test'): string {
    return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  },
};
