/**
 * {{PROJECT_NAME_PASCAL}} Vitest Configuration
 *
 * Modern test runner alternative to Jest.
 * Generated by bootstrap-test-suite.sh
 */

import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    // Test file patterns
    include: [
      '{{TESTS_DIR}}/**/*.test.ts',
      '{{TESTS_DIR}}/**/*.test.tsx',
      '{{TESTS_DIR}}/**/*.spec.ts',
      '{{TESTS_DIR}}/**/*.spec.tsx',
    ],

    // Exclude patterns
    exclude: [
      'node_modules',
      'dist',
      '.git',
      '{{TESTS_DIR}}/browser/**', // Use Playwright for browser tests
    ],

    // Environment
    environment: 'node',

    // Globals (jest-like)
    globals: true,

    // Coverage
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: '{{TESTS_DIR}}/coverage',
      exclude: [
        'node_modules',
        '{{TESTS_DIR}}',
        '**/*.d.ts',
        '**/*.config.*',
      ],
    },

    // Reporters
    reporters: ['verbose', 'html'],
    outputFile: {
      html: '{{TESTS_DIR}}/logs/latest/vitest-report.html',
    },

    // Timeouts
    testTimeout: 10000,
    hookTimeout: 10000,

    // Parallelization
    pool: 'threads',
    poolOptions: {
      threads: {
        singleThread: false,
      },
    },

    // Setup files
    setupFiles: ['{{TESTS_DIR}}/vitest.setup.ts'],
  },

  // Path aliases
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './{{SRC_DIR}}'),
      '@tests': path.resolve(__dirname, './{{TESTS_DIR}}'),
    },
  },
});
