/**
 * {{PROJECT_NAME_PASCAL}} Vitest Setup
 *
 * Global setup for Vitest test suite.
 * Generated by bootstrap-test-suite.sh
 */

import { beforeEach, afterEach, afterAll, vi } from 'vitest';

// Mock timers if needed
// vi.useFakeTimers();

// Global test utilities
export const testUtils = {
  /**
   * Wait for a condition to be true
   */
  async waitFor(
    condition: () => boolean | Promise<boolean>,
    timeout = 5000,
    interval = 100
  ): Promise<boolean> {
    const start = Date.now();
    while (Date.now() - start < timeout) {
      if (await condition()) return true;
      await new Promise(r => setTimeout(r, interval));
    }
    throw new Error(`Condition not met within ${timeout}ms`);
  },

  /**
   * Sleep for specified milliseconds
   */
  sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  },

  /**
   * Generate a unique test ID
   */
  uniqueId(prefix = 'test'): string {
    return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  },
};

// Make available globally
declare global {
  var testUtils: typeof testUtils;
}
globalThis.testUtils = testUtils;

// Console error tracking
let consoleErrors: unknown[][] = [];
const originalError = console.error;

beforeEach(() => {
  consoleErrors = [];
  console.error = (...args: unknown[]) => {
    consoleErrors.push(args);
    originalError.apply(console, args);
  };
});

afterEach(() => {
  console.error = originalError;
  vi.clearAllMocks();
});

afterAll(() => {
  vi.restoreAllMocks();
});
